### ISSUE TITLE
Some details about PIDM

### ISSUE THREAD

**Issue by mayuelala** [ankanbhunia/PIDM#1]
Thank you for your nice work ! 
 
1. Which dimension is used for concat between the Yt  and Xp？ （2 *  B C H W -> B C H 2W   or 2 * B C H W -> B 2C H W ？）

2. how to generate the Epose by Xp  in sampling?  concat the Yt and Xp ？ or other way

Looking forward to your reply. Again, Thanks for your awesome work! ;-)

**Comment by ankanbhunia** [comment]
Thanks for your interest.

1. Yt and Xp are concatenated along the channel dimension ie. 2 * B C H W -> B 2C H W.
2. I am not sure I understand this question. During inference, for t = T --> 1, we concate Yt and Xp, then pass it through the network, obtaining Y_(t-1). 
Note, the problem statement we are dealing with is **pose-guided** person image generation, here, the pose: Xp is given as input.
