### ISSUE TITLE
About keypoints estimation

### ISSUE THREAD

**Issue by noway2beatme** [ankanbhunia/PIDM#18]
Thanks for your great work! Really appreciate it!
I wonder if you could release the code of keypoint extraction for us to upload some customized model pictures as target pictures.

**Comment by ankanbhunia** [comment]
You can use [openpose](https://github.com/CMU-Perceptual-Computing-Lab/openpose) to extract the keypoints. Specifically, we perform 18-keypoint estimation. The keypoints are saved in a txt file as (18, 2) coordinate points. To know how we process those keypoints, you can check [this file](https://github.com/ankanbhunia/PIDM/blob/2b34cac8cef7ba896384905f1f37b2296653b6e9/data/fashion_data.py#L389) inside the ```data``` folder. The ```get_label_tensor``` function is used to process the keypoints to obtain a tensor of size ```[bs, 20, H, W]```.

**Comment by chenbolin-master** [comment]
@ankanbhunia   I get the keypoints.json from openpose , but how to get the  reference_pose_0.npy ? thanks.
