### ISSUE TITLE
Plans for providing the training and testing code

### ISSUE THREAD

**Issue by juxuan27** [ankanbhunia/PIDM#2]
Hi! I appreciate your excellent work. Do you have any plans for making the testing and training code available? This topic interests me and I can't wait to try it on my own.

**Comment by mayuelala** [comment]
Also，So perfect work！ I want to follow your work to do some research！Thanks

**Comment by ankanbhunia** [comment]
Thanks for your interest. I will upload the code as soon as possible but can't promise any timeline as of now. 
Put this repo in your watchlist and stay tuned.
