### ISSUE TITLE
How to start with the code

### ISSUE THREAD

**Issue by Maram-Helmy** [ankanbhunia/PIDM#22]
Many Thanks for sharing the code! I'm new to this and I'm not sure how can I start debugging the code. I want to first debug the code on my local machine which has very limited GPU before I run it on the sever (which has a 12 GB GPU). I'm using visual studio code. I would really appreciate if you can guide me in this and how can I run the code on a single GPU. Your input is highly appreciated.

Many thanks again.

**Comment by ankanbhunia** [comment]
You can use --nproc_per_node=1 and reduce the batch_size based on your gpu memory.
