### ISSUE TITLE
custom dataset training

### ISSUE THREAD

**Issue by saisritejakuppa** [ankanbhunia/PIDM#23]
Can you explain how to train with custom dataset and provide a sample format how it would look like?

**Comment by saisritejakuppa** [comment]
I don't wanna use the key points from openpose, rather I have a database from media pipe, can you explain the final structure of files, and how they have to aligned? 
Thanks in advance.
@ankanbhunia

**Comment by ZhenyanSun** [comment]
+1

**Comment by Maram-Helmy** [comment]
+1

**Comment by ankanbhunia** [comment]
The file structure is as follows:

- dataset/
- - <dataset_name>/
- - - img/ 
- - - - <person_id>_<image_id>.png
- - - - ...
- - - pose/
- - - - <person_id>_<image_id>.txt
- - - - .....
- - - train_pairs.txt
- - - test_pairs.txt

You basically will have all your images inside ```img``` folder. You can use different subfolders to store your images or put all your images inside ```img``` folder as well. The corresponding poses are stored inside ```pose``` folder (as txt file if you use openpose. In our project, we use 18-point keypoint estimation). ```train_pairs.txt``` and ```test_pairs.txt``` will have paths of all possible pairs seperated by comma ```<src_path1>,<tgt_path1>```.

After that, run the following command to process the data:

```
python data/prepare_data.py \
--root ./dataset/<dataset_name> \
--out ./dataset/<dataset_name>
--sizes ((256,256),)
```

This will create an lmdb dataset ```./dataset/<dataset_name>/256-256/```
