### ISSUE TITLE
About the ddim_steps function in deffusion.py

### ISSUE THREAD

**Issue by noway2beatme** [ankanbhunia/PIDM#25]
x_cond[0][0] = [torch.stack([i * feat[0] + (1 - i) * feat[-1] for i in torch.linspace(0, 1, len(feat))], 0) for feat in x_cond[0][0]]

What does this line of computation do?

**Comment by noway2beatme** [comment]
Thank you!

**Comment by ankanbhunia** [comment]
I appreciate you bringing this to my attention. This line was supposed to be commented out, but I must have missed it and it went unnoticed. However, this line had no impact on the inference or in the colab demo file where bs is set to 1. 

The DDPM sampling is okay.
