### ISSUE TITLE
About the training images

### ISSUE THREAD

**Issue by zhangjialun0** [ankanbhunia/PIDM#26]
Thanks for your great work!

I find the training dataset that you offer is 256x256，but the original image is 256x176，I want to know the way to turn 256x176 into 256x256.

Thanks again!

**Comment by ankanbhunia** [comment]
We resize the images. Specifically, we use Image.BICUBIC (antialiasing) as interpolation method in the resize function.

**Comment by zhangjialun0** [comment]
Thank you for your reply.
My expression may have misunderstood you.

I find the high resolution image is different from then 256 image, it seems like you added white area on both sides, and I find the left and right blank areas are not the same size in some images.  I want to know how you did it.

The example is as follows: (WOMEN/Blouses_Shirts/id_00000001/02_1_front.jpg)

![02_1_front](https://user-images.githubusercontent.com/43677933/233248297-a60b2169-7fe0-4e5d-aa26-b23d09ea1357.jpg)

![02_1_front](https://user-images.githubusercontent.com/43677933/233248369-eb3db03b-501d-45c1-ab20-e5682c22ec77.jpg)


Thanks again!

**Comment by zhangjialun0** [comment]
I find trans_keypoins in data/fashion_data.py :
keypoints[:,0] = (keypoints[:,0]-40)
Does it mean if I want to train 512*352 , I can use the same pose.txt as 256 without keypoints[:,0]-40

**Comment by ankanbhunia** [comment]
> I find the high resolution image is different from then 256 image, it seems like you added white area on both sides, and I find the left and right blank areas are not the same size in some images. I want to know how you did it.

Have you used the ```prepare_data.py``` file to create the lmdb dataset? Could you also let me know how you obtained the first image (the low-res one). It would help me to debug as I think there should not be any white space on the both sides. 


> I find trans_keypoins in data/fashion_data.py : keypoints[:,0] = (keypoints[:,0]-40) Does it mean if I want to train 512*352 , I can use the same pose.txt as 256 without keypoints[:,0]-40

The dataloader code would remain same. You just need to create a new lmdb using ```prepare_data.py```. You can set your required image-size in the --sizes argument while running this file.

**Comment by gouchaonijiao** [comment]
你好! 请问你知道怎么制作更多的'data/deepfashion_256x256/target_pose/*.npy'文件吗?

**Comment by zhangjialun0** [comment]
Thanks, I create a new lmdb using prepare_data.py and I am trainning successfully.  By the way, how many epochs have you trained on 512*352

**Comment by ankanbhunia** [comment]
200 epochs | 300k iterations with batchsize:8 and no_gpu:8

**Comment by zhangjialun0** [comment]
THANKS!
