### ISSUE TITLE
About Market-1501 Experiments

### ISSUE THREAD

**Issue by YanzuoLu** [ankanbhunia/PIDM#32]
Thanks for your excellent work and generous sharing in the repo.

I want to make sure one thing about ReID experiments in the paper.

Are synthesized images generated from a model that trained from scratch on Market-1501 training set?
Since I observed that its resolution (128x64) is different from DeepFashion, I'm quite confused about this.

**Comment by ankanbhunia** [comment]
Yes, Market-1501 models are trained from scratch.
