### ISSUE TITLE
SSIM, FID and PSNR

### ISSUE THREAD

**Issue by leetcodevis13** [ankanbhunia/PIDM#33]
Hi authors, your work is impressive. Thanks for sharing the code base. However, I couldn't find the evaluation code for SSIM, PSNR, and FID. It would greatly help the community if you could share it. Looking forward to your kind response.

**Comment by ankanbhunia** [comment]
Please use the file ```utils/metrics.py``` for the evaluation code for SSIM, PSNR, and FID.

**Comment by leetcodevis13** [comment]
Awesome! Thanks :)
