### ISSUE TITLE
SSIM params

### ISSUE THREAD

**Issue by BrandonHanx** [ankanbhunia/PIDM#4]
Hi,

Could you please tell me what's your params for ssim calculation?
I cannot get the same number with your shared generative images.

Cheers

**Comment by ankanbhunia** [comment]
Thanks for your interest. Could you please tell me if you were able to reproduce the FID and LPIPS scores? And what score are you getting for SSIM?

**Comment by BrandonHanx** [comment]
Hi,

I found some reference codes in the previous works repo.
I achieved the same number (71.68) as the metrics.npz in your shared folder.

So I was just wondering if the provided images are your final results?

**Comment by BrandonHanx** [comment]
@ankanbhunia Can you share more details? FID and LPIPS also cannot be reproduced. I am based on GFLA eval script.

**Comment by ankanbhunia** [comment]
What numbers you are getting for FID and LPIPS? I have re-calculated the scores and got the following numbers:

<img width="1122" alt="Screenshot 2023-02-18 at 9 01 30 PM" src="https://user-images.githubusercontent.com/26159099/219874537-2b52b5eb-34ad-4d3b-b42e-3bc83fe34084.png">

Few questions to reproduce the issue: 
How are you saving the real images?
Which format (.png/jpeg) are you using?
Did you resize the real images to 256x256 before saving?
What resizing method and library are you using?

One should use 1) .png format to save (as it's lossless) 2) BICUBIC from PIL library to resize (antialiasing).

**Comment by BrandonHanx** [comment]
Thanks for your response.

Yes, I resized as png with PIL bicubic resize function.
My results are FID 6.4362, SSIM 0.7109, LPIPS 0.1685.
FID and LPIPS are almost the same here.
But for SSIM, did you check the `metrics.npz` in your shared folder? It's also ~0.71.

**Comment by WeiYu021** [comment]
I also have some questions. The result of the network is of 256 * 256 resolution. When I calculated the score, I resized the result to 256 * 176 and compared it with the orginal one. How to produce the original one, resize from **the original resolution** to **256 * 176** or resize from **256 * 256** (which resize from the original resolution) to **256 * 176**? I' ve tested these two ways and got different results.
