### ISSUE TITLE
The Question about Figure 3 in Paper?

### ISSUE THREAD

**Issue by muzishen** [ankanbhunia/PIDM#43]
1. I want to cite it and compare, but I don't know the ID name of these images.
2. Could you provide the result's size of Fig. 3? I feel like it's not a square，e.g., 256x256 or 512x512.

**Comment by ankanbhunia** [comment]
1. check this [PIDM_vs_Others.zip](https://drive.google.com/file/d/1iu75RVQBjR-TbB4ZQUns1oalzYZdNqGS/view?usp=share_link) for ids. 
2. originally generated as 256X256 then resized to 176X256.

**Comment by muzishen** [comment]
Thank you for your prompt reply ！！！
