### ISSUE TITLE
Question on pose-target data

### ISSUE THREAD

**Issue by Mut1nyJD** [ankanbhunia/PIDM#6]
Thank you for this interesting work and releasing the inference demo. I am currently also working on a pose conditional generation model so I was curious about your solution. I noticed that your pose targets contain 20 channels which surprised me with further inspection I saw that the first 3 channels are basically a visualization of the  pose skeleton and the other 17 channels the usual gaussian key point maps. 

I wonder what the rational of including the skeleton visualization is? Does it lead to any significant improvement feeding that into the model along side the keypoint maps?

Thank you

**Comment by ankanbhunia** [comment]
Thanks for your interest. I don't think there will be any difference. Also, we are not the first to use 20-channel pose skeletons; there are some previous works that have also used similar pose repr.

**Comment by Mut1nyJD** [comment]
@ankanbhunia Thank you for your answer. Ok I did not know others have been doing this too. Well 3 extra channels are just eating up more VRAM so if they are not necessary I was wondering. But I guess I have to try myself and see if there is any impact
