### ISSUE TITLE
Is the model you use actually BeatGANsAutoencModel and it has no cross attention?

### ISSUE THREAD

**Issue by safeanimal** [ankanbhunia/PIDM#68]
Am I wrong? I exmained the code and found that it actually uses BeatGANsAutoencModel, I don't see any cross attention in it, it's different from the method you use in the paper.

**Comment by ankanbhunia** [comment]
see https://github.com/ankanbhunia/PIDM/blob/e4f1d880772072ee464a83240d0374bf466b6772/models/blocks.py#L471

Follow the code: AttentionBlock -> ResBlock -> BeatGANsAutoencModel

**Comment by safeanimal** [comment]
> see
> 
> https://github.com/ankanbhunia/PIDM/blob/e4f1d880772072ee464a83240d0374bf466b6772/models/blocks.py#L471
> 
> Follow the code: AttentionBlock -> ResBlock -> BeatGANsAutoencModel

ok, thank you, I mistook AttentionBlock as a self-attention.
